name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Install dependencies
        run: |
          npm install -g @angular/cli
          npm install

      - name: Build
        run: |
          ng build --configuration production --base-href=/Fyle-Assignment/
          cd dist/fyle-challenge
          cp index.html 404.html
          touch .nojekyll
          ls -la  # List files to verify

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/fyle-challenge
          branch: gh-pages
          clean: true
          clean-exclude: |
            .nojekyll
            404.html
            index.html 